---
name: Setup
description: Setup Python and install dependencies.

inputs:
  python_version:
    description: The Python version.
    required: false
    default: '3.9'
  uv_version:
    description: The uv version.
    required: false
    default: '0.11.21'

runs:
  using: composite
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ inputs.uv_version }}
        python-version: ${{ inputs.python_version }}
        enable-cache: true
    - name: Install dependencies
      shell: bash
      run: uv sync
